### PR TITLE
New post: Building a mini Twitter clone with Spark

### PR DESCRIPTION
**Pull request by eh3rrera**
Hi, I wrote a tutorial for the site, here's the summary:

> This tutorial will walk you through the steps of creating a mini Twitter clone using Spark, Freemarker, Spring, and HSQLDB to show you how to build a simple but complete web application.

The complete code of this application is available on https://github.com/eh3rrera/minitwit. It's based on the [minitwit](http://github.com/mitsuhiko/flask/tree/master/examples/minitwit/) Flask example.

Any feedback is welcome.

### CODE REVIEW

**Comment by leonanluppi** [comment]
Very good! Thanks for contribution @eh3rrera.

**Comment by eh3rrera** [comment]
Thanks @leonanluppi

**Comment by ftomassetti** [comment]
Thank you guys!

**Comment by tipsy** [comment]
@eh3rrera, I'm sorry about not noticing this before. I'll go through it later today.

**Comment by tipsy** [comment]
@eh3rrera, seems great, thanks a lot for your work. 
It's published now, we'll promote it a little later :)

**Comment by eh3rrera** [comment]
Great, no problem. Thanks @tipsy and @ftomassetti

**Pull request merged**
